name: CI/CD for C#

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore D:\a\ИСРПО\GIT_test\GIT_test\makefile_test\makefile_test.sin

      - name: Build project
        run: dotnet build D:\a\ИСРПО\GIT_test\GIT_test\makefile_test\makefile_test.sin --no-restore

      - name: Run tests
        run: dotnet test D:\a\ИСРПО\GIT_test\GIT_test\makefile_test\makefile_test.sin --no-build --verbosity normal